version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::303579314896:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-4BOEMGO9HIVG"
permissions_provider = "AWS IAM"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::303579314896:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1EXGMRU8M7PIU"
cloudformation_execution_role = "arn:aws:iam::303579314896:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-13FN6CKHSS9UA"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-1awxr7qt59hmv"
image_repository = ""
region = "us-east-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::303579314896:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-4XY2T6DD709P"
cloudformation_execution_role = "arn:aws:iam::303579314896:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-T003PXI11F8R"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-1ge2v1j4m3vbz"
image_repository = ""
region = "us-east-1"
