# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  its-on

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  Env:
    Type: String
    Default: local
    Description: Environment name - used to populate stack names and subdomains
  PipelineRole:
    Type: String
  SnsCognitoIamExternalId:
    Type: String
  SnsCognitoIamArn:
    Type: String
  SESDomainIdentityArn:
    Type: String

Conditions:
  IsProdEnv: !Equals [!Ref Env, prod]

# Mappings:
# If you're trying to refactor the urls here,
# conditions don't work in the mappings section.
# Just ask Bard.

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  #Backend Resources
  ItsOnApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Env
      Cors:
        AllowCredentials: false
        AllowHeaders: "'*, Authorization'"
        AllowMethods: "'OPTIONS, POST, GET'"
        AllowOrigin: "'*'"
        MaxAge: 600
      Auth:
        DefaultAuthorizer: ItsOnCognitoAuthorizer
        Authorizers:
          ItsOnCognitoAuthorizer:
            UserPoolArn: !GetAtt ItsOnUserPool.Arn
      Domain:
        CertificateArn: arn:aws:acm:us-east-1:303579314896:certificate/89fd3c8f-9ccb-479e-b61a-36987061371e
        DomainName:
          "Fn::If":
            - IsProdEnv
            - api.itson.fyi
            - !Sub ${Env}.api.itson.fyi
        Route53:
          EvaluateTargetHealth: true
          HostedZoneId: Z06575223EAH4XQ5M1AVF

  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: get-all-items.js
  getAllItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-all-items.getAllItemsHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get all items from a DynamoDB table.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the ItsOnTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ItsOnTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          ITS_ON_TABLE: !Ref ItsOnTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ItsOnApi
            Path: /
            Method: GET
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: get-by-id.js
  getByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-by-id.getByIdHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get one item by id from a DynamoDB table.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the ItsOnTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ItsOnTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          ITS_ON_TABLE: !Ref ItsOnTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ItsOnApi
            Path: /{id}
            Method: GET
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: put-item.js
  putItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/put-item.putItemHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the ItsOnTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ItsOnTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          ITS_ON_TABLE: !Ref ItsOnTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ItsOnApi
            Path: /
            Method: POST

  tableStreamFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/table-stream.tableStreamHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Handles write events from the ItsOnTable
      Policies:
        # Give Create/Read/Update/Delete Permissions to the ItsOnTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ItsOnTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          ITS_ON_TABLE: !Ref ItsOnTable
      Events:
        TableStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt ItsOnTable.StreamArn
            StartingPosition: LATEST
            # BatchSize: 10
            # MaximumBatchingWindowInSeconds: 10
            # Enabled: true
            # ParallelizationFactor: 1
            # MaximumRetryAttempts: 10
            # BisectBatchOnFunctionError: true
            # MaximumRecordAgeInSeconds: 86400
            # DestinationConfig:
            #   OnFailure:
            #     Type: SQS
            #     Destination: !GetAtt MySqsQueue.Arn
            # TumblingWindowInSeconds: 0
            # FunctionResponseTypes:
            #   - ReportBatchItemFailures

  # DynamoDB table to store item: {id: &lt;ID&gt;, name: &lt;NAME&gt;}
  ItsOnTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      DeletionProtectionEnabled:
        "Fn::If":
          - IsProdEnv
          - true
          - false
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      Tags:
        - Key: project
          Value: itson
        - Key: env
          Value: !Ref Env

  # Auth Resources
  ItsOnUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      # TODO: UserPool: Decide if this would be better for development
      # Definitely safer...
      # How would devs move fast in feature environments?
      # AdminCreateUserConfig:
      #   AllowAdminCreateUserOnly:
      #     "Fn::If":
      #       - IsProdEnv
      #       - false
      #       - true
      AliasAttributes:
        - email
        - phone_number
        - preferred_username
      AutoVerifiedAttributes:
        - email
        - phone_number
      DeletionProtection:
        "Fn::If":
          - IsProdEnv
          - ACTIVE
          - INACTIVE
      DeviceConfiguration:
        ChallengeRequiredOnNewDevice: true
        DeviceOnlyRememberedOnUserPrompt: false
      EmailConfiguration:
        # ConfigurationSet: Used for event monitoring and ip management
        EmailSendingAccount: DEVELOPER
        From: no-reply@itson.fyi
        ReplyToEmailAddress: no-reply@itson.fyi
        SourceArn: !Ref SESDomainIdentityArn
      EnabledMfas:
        - SMS_MFA
        - SOFTWARE_TOKEN_MFA
      MfaConfiguration: OPTIONAL
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireUppercase: true
      Schema:
        - AttributeDataType: String
          Name: email
          Required: true
        - AttributeDataType: String
          Name: name
          Required: false
        - AttributeDataType: String
          Name: phone_number
          Required: false # TODO: UserPool: phone number based sign-up?
        - AttributeDataType: String
          Name: preferred_username
          Required: false
      SmsConfiguration:
        ExternalId: !Ref SnsCognitoIamExternalId
        SnsCallerArn: !Ref SnsCognitoIamArn
        SnsRegion: us-east-1
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate:
          - phone_number
          - email
      UsernameConfiguration:
        CaseSensitive: false
      # TODO: UserPool: Delete if not needed
      # UsernameAttributes:
      #   - phone_number
      #   - email
      # TODO: UserPool: Enable on Launch
      # UserPoolAddOns:
      #   AdvancedSecurityMode:
      #     "Fn::If":
      #       - IsProdEnv
      #       - AUDIT # Audit for a couple of weeks then switch to ENFORCE
      #       - OFF
      UserPoolName: !Sub ItsOnUsers-${Env}

  ItsOnUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      AllowedOAuthFlows:
        - code
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - email
        - phone
        - profile
        - openid
      CallbackURLs:
        - "Fn::If":
            - IsProdEnv
            - https://itson.fyi/
            - !Sub https://${Env}.itson.fyi/
        - "Fn::If":
            - IsProdEnv
            - !Ref AWS::NoValue
            - http://localhost:3000/
      ClientName: !Sub ItsOnUsersClient-${Env}
      DefaultRedirectURI:
        "Fn::If":
          - IsProdEnv
          - https://itson.fyi/
          - !Sub https://${Env}.itson.fyi/
      GenerateSecret: false
      LogoutURLs:
        - "Fn::If":
            - IsProdEnv
            - https://itson.fyi/
            - !Sub https://${Env}.itson.fyi/
        - "Fn::If":
            - IsProdEnv
            - !Ref AWS::NoValue
            - http://localhost:3000/
      SupportedIdentityProviders:
        - COGNITO
      UserPoolId: !Ref ItsOnUserPool

  ItsOnUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      CustomDomainConfig:
        CertificateArn: arn:aws:acm:us-east-1:303579314896:certificate/89fd3c8f-9ccb-479e-b61a-36987061371e
      Domain:
        "Fn::If":
          - IsProdEnv
          - auth.itson.fyi
          - !Sub ${Env}-auth.itson.fyi
      UserPoolId: !Ref ItsOnUserPool

  # Front End Resources
  ItsOnFrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        "Fn::If":
          - IsProdEnv
          - itson.fyi
          - !Sub ${Env}.itson.fyi
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  ItsOnCloudFrontCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        DefaultTTL: 86400
        MaxTTL: 172800
        MinTTL: 3600
        Name: !Sub ItsOnCloudFrontCachePolicy-${Env}
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingGzip: false
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none

  ItsOnCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: Cloudfront Distribution pointing to S3 bucket
        Origins:
          - Id: ItsOnFrontendBucket
            DomainName:
              !Select [2, !Split ["/", !GetAtt ItsOnFrontendBucket.WebsiteURL]]
            CustomOriginConfig:
              HTTPPort: "80"
              HTTPSPort: "443"
              OriginProtocolPolicy: http-only
          - Id: ItsOnApi
            DomainName:
              "Fn::If":
                - IsProdEnv
                - api.itson.fyi
                - !Sub ${Env}.api.itson.fyi
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        Enabled: true
        HttpVersion: "http2"
        DefaultRootObject: index.html
        Aliases:
          - "Fn::If":
              - IsProdEnv
              - itson.fyi
              - !Sub ${Env}.itson.fyi
        DefaultCacheBehavior:
          AllowedMethods: [GET, HEAD, OPTIONS, PUT, PATCH, POST, DELETE]
          CachePolicyId: !Ref ItsOnCloudFrontCachePolicy
          Compress: true
          TargetOriginId: ItsOnFrontendBucket
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:303579314896:certificate/89fd3c8f-9ccb-479e-b61a-36987061371e
          SslSupportMethod: sni-only

  ItsOnFrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: ItsOnFrontEndPolicy
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref PipelineRole
            Action: "*"
            Resource:
              - !Sub
                - "arn:aws:s3:::${Bucket}/*"
                - Bucket: !Ref ItsOnFrontendBucket
              - !Sub
                - "arn:aws:s3:::${Bucket}"
                - Bucket: !Ref ItsOnFrontendBucket
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource:
              - !Sub
                - "arn:aws:s3:::${Bucket}/*"
                - Bucket: !Ref ItsOnFrontendBucket
      Bucket: !Ref ItsOnFrontendBucket

  # DNS
  ItsOnDNSName:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: Z06575223EAH4XQ5M1AVF
      RecordSets:
        - Name:
            "Fn::If":
              - IsProdEnv
              - itson.fyi
              - !Sub ${Env}.itson.fyi
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt ItsOnCloudFrontDistribution.DomainName
        - Name:
            "Fn::If":
              - IsProdEnv
              - auth.itson.fyi
              - !Sub ${Env}-auth.itson.fyi
          ResourceRecords:
            - !GetAtt ItsOnUserPoolDomain.CloudFrontDistribution
          TTL: 60
          Type: CNAME

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL for given env"
    Value:
      "Fn::If":
        - IsProdEnv
        - https://api.itson.fyi
        - !Sub https://${Env}.api.itson.fyi
  AuthEndpoint:
    Description: "Cognito Hosted UI endpoint URL for given env"
    Value:
      "Fn::If":
        - IsProdEnv
        - https://auth.itson.fyi
        - !Sub https://${Env}-auth.itson.fyi
  CognitoClientID:
    Value: !Ref ItsOnUserPoolClient
  ItsOnFrontendBucketName:
    Value:
      "Fn::If":
        - IsProdEnv
        - itson.fyi
        - !Sub ${Env}.itson.fyi
  WebEndpoint:
    Description: "Web endpoint URL for given env (prod has no subdomain)"
    Value:
      "Fn::If":
        - IsProdEnv
        - https://itson.fyi
        - !Sub https://${Env}.itson.fyi
  Website:
    Value: !GetAtt ItsOnCloudFrontDistribution.DomainName
