# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  its-on

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  PipelineRole:
    Type: String
  Env:
    Type: String
    Default: local
    Description: Environment name - used to populate stack names and subdomains

Conditions:
  IsProdEnv: !Equals [!Ref Env, prod]

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  ItsOnApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Env
      Cors: "'*'"
      Auth:
        DefaultAuthorizer: ItsOnCognitoAuthorizer
        Authorizers:
          ItsOnCognitoAuthorizer:
            UserPoolArn: !GetAtt ItsOnCognitoUserPool.Arn
      Domain:
        CertificateArn: arn:aws:acm:us-east-1:303579314896:certificate/89fd3c8f-9ccb-479e-b61a-36987061371e
        DomainName:
          "Fn::If":
            - IsProdEnv
            - api.itson.fyi
            - !Sub ${Env}.api.itson.fyi
        Route53:
          EvaluateTargetHealth: true
          HostedZoneId: Z06575223EAH4XQ5M1AVF

  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: get-all-items.js
  getAllItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-all-items.getAllItemsHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get all items from a DynamoDB table.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the ItsOnTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ItsOnTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          ITS_ON_TABLE: !Ref ItsOnTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ItsOnApi
            Path: /
            Method: GET
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: get-by-id.js
  getByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-by-id.getByIdHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get one item by id from a DynamoDB table.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the ItsOnTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ItsOnTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          ITS_ON_TABLE: !Ref ItsOnTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ItsOnApi
            Path: /{id}
            Method: GET
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: put-item.js
  putItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/put-item.putItemHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the ItsOnTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ItsOnTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          ITS_ON_TABLE: !Ref ItsOnTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ItsOnApi
            Path: /
            Method: POST
  # Simple syntax to create a DynamoDB table with a single attribute primary key, more in
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlesssimpletable

  # DynamoDB table to store item: {id: &lt;ID&gt;, name: &lt;NAME&gt;}
  ItsOnTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  ItsOnCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ItsOnUsers-${Env}
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false

  ItsOnCognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      AllowedOAuthFlows:
        - code
        # For security reasons, we recommend that you use the authorization
        # code grant flow, together with Proof Key for Code Exchange (PKCE),
        # for mobile apps. https://tools.ietf.org/html/rfc7636
        - implicit # TODO: REMOVE
      AllowedOAuthScopes:
        - email
        - phone
        - profile
        - openid
      CallbackURLs:
        - "Fn::If":
            - IsProdEnv
            - https://itson.fyi
            - !Sub https://${Env}.itson.fyi
      ClientName: !Sub ItsOnUsersClient-${Env}
      GenerateSecret: false
      SupportedIdentityProviders:
        - COGNITO
      UserPoolId: !Ref ItsOnCognitoUserPool

  ItsOnCognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      CustomDomainConfig:
        CertificateArn: arn:aws:acm:us-east-1:303579314896:certificate/89fd3c8f-9ccb-479e-b61a-36987061371e
      Domain:
        "Fn::If":
          - IsProdEnv
          - auth.itson.fyi
          - !Sub ${Env}-auth.itson.fyi
      UserPoolId: !Ref ItsOnCognitoUserPool

  ItsOnFrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        "Fn::If":
          - IsProdEnv
          - itson.fyi
          - !Sub ${Env}.itson.fyi
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
    DeletionPolicy: Retain

  ItsOnCloudFrontCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        DefaultTTL: 86400
        MaxTTL: 172800
        MinTTL: 3600
        Name: !Sub ItsOnCloudFrontCachePolicy-${Env}
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingGzip: false
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none

  ItsOnCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - ItsOnFrontendBucket
      - ItsOnCloudFrontCachePolicy
    Properties:
      DistributionConfig:
        Comment: Cloudfront Distribution pointing to S3 bucket
        Origins:
          - Id: ItsOnFrontendBucket
            DomainName:
              !Select [2, !Split ["/", !GetAtt ItsOnFrontendBucket.WebsiteURL]]
            CustomOriginConfig:
              HTTPPort: "80"
              HTTPSPort: "443"
              OriginProtocolPolicy: http-only
          - Id: ItsOnApi
            DomainName:
              "Fn::If":
                - IsProdEnv
                - api.itson.fyi
                - !Sub ${Env}.api.itson.fyi
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        Enabled: true
        HttpVersion: "http2"
        DefaultRootObject: index.html
        Aliases:
          - "Fn::If":
              - IsProdEnv
              - itson.fyi
              - !Sub ${Env}.itson.fyi
        DefaultCacheBehavior:
          AllowedMethods: [GET, HEAD, OPTIONS, PUT, PATCH, POST, DELETE]
          CachePolicyId: !Ref ItsOnCloudFrontCachePolicy
          Compress: true
          TargetOriginId: ItsOnFrontendBucket
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:303579314896:certificate/89fd3c8f-9ccb-479e-b61a-36987061371e
          SslSupportMethod: sni-only

  ItsOnFrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: ItsOnFrontEndPolicy
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref PipelineRole
            Action: "*"
            Resource:
              - !Sub
                - "arn:aws:s3:::${Bucket}/*"
                - Bucket: !Ref ItsOnFrontendBucket
              - !Sub
                - "arn:aws:s3:::${Bucket}"
                - Bucket: !Ref ItsOnFrontendBucket
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource:
              - !Sub
                - "arn:aws:s3:::${Bucket}/*"
                - Bucket: !Ref ItsOnFrontendBucket
      Bucket: !Ref ItsOnFrontendBucket

  ItsOnDNSName:
    Type: AWS::Route53::RecordSetGroup
    DependsOn:
      - ItsOnCloudFrontDistribution
    Properties:
      HostedZoneId: Z06575223EAH4XQ5M1AVF
      RecordSets:
        - Name:
            "Fn::If":
              - IsProdEnv
              - itson.fyi
              - !Sub ${Env}.itson.fyi
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt ItsOnCloudFrontDistribution.DomainName
        - Name:
            "Fn::If":
              - IsProdEnv
              - auth.itson.fyi
              - !Sub ${Env}-auth.itson.fyi
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt ItsOnCognitoUserPoolDomain.CloudFrontDistribution

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL for given env (prod has no subdomain)"
    Value: !Sub "https://${Env}.api.itson.fyi/"
  WebEndpoint:
    Description: "Web endpoint URL for given env (prod has no subdomain)"
    Value: !Sub "https://${Env}.itson.fyi/"
  Website:
    Value: !GetAtt ItsOnCloudFrontDistribution.DomainName
  ItsOnFrontendBucketName:
    Value:
      "Fn::If":
        - IsProdEnv
        - itson.fyi
        - !Sub ${Env}.itson.fyi
