import { APIGatewayProxyEvent } from 'aws-lambda'

const mockEvent: APIGatewayProxyEvent = {
  headers: {
    accept: '*/*',
    'content-length': '6865',
    'content-type': 'application/json',
    host: '',
    'user-agent': 'GitHub-Hookshot/f7fae6a',
    'x-amzn-trace-id': '',
    'x-forwarded-for': '127.0.0.1',
    'x-forwarded-port': '443',
    'x-forwarded-proto': 'https',
    'x-github-delivery': 'd59ed4f0-062b-11ed-8d67-5795d0322825',
    'x-github-event': 'star',
    'x-github-hook-id': '369182928',
    'x-github-hook-installation-target-id': '513387854',
    'x-github-hook-installation-target-type': 'repository',
    'x-hub-signature': 'sha1=214b0127c9e92d2899b6739f215e33bf4168a668',
    'x-hub-signature-256':
      'sha256=c2af8d2bc59689c28094b194bc3a38ed865c2ea4de38ca90dd6d71c61d2e12ef',
  },
  requestContext: {
    accountId: '123123123',
    apiId: '[redacted]',
    authorizer: {
      claims: {
        'cognito:username': 'test_user',
        sub: '00000000-0000-0000-0000-000000000000',
      },
    },
    domainName: '[redacted]',
    domainPrefix: '[redacted]',
    httpMethod: 'GET',
    identity: {
      accessKey: null,
      accountId: null,
      apiKey: null,
      apiKeyId: null,
      caller: null,
      clientCert: null,
      cognitoAuthenticationProvider: null,
      cognitoAuthenticationType: null,
      cognitoIdentityId: null,
      cognitoIdentityPoolId: null,
      principalOrgId: null,
      sourceIp: '0.0.0.0',
      user: null,
      userAgent: null,
      userArn: null,
    },
    path: '/',
    protocol: 'HTTP/1.1',
    requestId: 'Vb4i_hboIAMEVMA=',
    requestTimeEpoch: 1658102086166,
    resourceId: '0',
    resourcePath: '/',
    routeKey: 'GET /',
    stage: 'mock_stage',
  },
  body: '',
  isBase64Encoded: false,
  multiValueHeaders: {},
  httpMethod: '',
  path: '',
  pathParameters: null,
  queryStringParameters: null,
  multiValueQueryStringParameters: null,
  stageVariables: null,
  resource: '',
}

export default mockEvent
