name: Push Main

on:
  push:
    branches:
      - 'main'

env:
  AWS_REGION: us-east-1
  PROD_STACK_NAME: its-on-prod
  PROD_ARTIFACTS_BUCKET: its-on-prod-artifacts
  PROD_CLOUDFORMATION_EXECUTION_ROLE: arn:aws:iam::992382488292:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-5LY7VkKQdvm7
  PROD_PIPELINE_EXECUTION_ROLE: arn:aws:iam::992382488292:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-L5iZbwAPusQH
  PUSH_NOTIFICATION_PUBLIC_KEY: ${{ secrets.PUSH_NOTIFICATION_PUBLIC_KEY }}
  PUSH_NOTIFICATION_PRIVATE_KEY: ${{ secrets.PUSH_NOTIFICATION_PRIVATE_KEY }}
  SAM_TEMPLATE: template.yml
  TESTING_STACK_NAME: its-on-test
  TESTING_ARTIFACTS_BUCKET: its-on-testing-artifacts
  TESTING_CLOUDFORMATION_EXECUTION_ROLE: arn:aws:iam::992382488292:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-DoShwApzYF47
  TESTING_PIPELINE_EXECUTION_ROLE: arn:aws:iam::992382488292:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-fAuX9MNwbZ4E

permissions:
  id-token: write
  contents: read

jobs:
  test-backend:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - run: rm -rf node_modules && yarn install --frozen-lockfile
      - run: yarn test-ci

  lint-backend:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - run: rm -rf node_modules && yarn install --frozen-lockfile
      - run: yarn lint

  compile-backend:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - run: rm -rf node_modules && yarn install --frozen-lockfile
      - run: yarn compile

  test-frontend:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - run: rm -rf node_modules && yarn install --frozen-lockfile
      - run: CI=true yarn test

  lint-frontend:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - run: rm -rf node_modules && yarn install --frozen-lockfile
      - run: yarn lint

  compile-frontend:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - run: rm -rf node_modules && yarn install --frozen-lockfile
      - run: tsc

  build-and-package-prod-api:
    if: github.ref == 'refs/heads/main'
    needs:
      [
        test-backend,
        lint-backend,
        compile-backend,
        test-frontend,
        lint-frontend,
        compile-frontend,
      ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - uses: aws-actions/setup-sam@v3
        with:
          use-installer: true
      - run: rm -rf node_modules && yarn install --frozen-lockfile
      # Remove all unit tests to reduce the size of the package that will be ultimately uploaded to Lambda
      - run: rm -rf ./__tests__
      - run: yarn compile
      - run: rm -rf node_modules && yarn install --production --frozen-lockfile
      - run: yarn set-up-layers
      - name: Build resources
        run: |
          yarn build \
            --template ${SAM_TEMPLATE} \
            --parameter-overrides \
              ParameterKey=Env,ParameterValue=prod \
              ParameterKey=PipelineRole,ParameterValue=${PROD_PIPELINE_EXECUTION_ROLE} \
              ParameterKey=PushNotificationPublicKey,ParameterValue=${PUSH_NOTIFICATION_PUBLIC_KEY} \
              ParameterKey=PushNotificationPrivateKey,ParameterValue=${PUSH_NOTIFICATION_PRIVATE_KEY}

      - name: Assume the testing pipeline user role
        uses: aws-actions/configure-aws-credentials@v6.1.1
        with:
          role-to-assume: ${{ env.TESTING_PIPELINE_EXECUTION_ROLE }}
          role-session-name: testing-packaging
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload artifacts to testing artifact buckets
        run: |
          sam package \
            --s3-bucket ${TESTING_ARTIFACTS_BUCKET} \
            --region ${AWS_REGION} \
            --output-template-file packaged-testing.yml

      - uses: actions/upload-artifact@v6
        with:
          name: packaged-testing.yml
          path: backend/packaged-testing.yml
          if-no-files-found: error

      - name: Assume the prod pipeline user role
        uses: aws-actions/configure-aws-credentials@v6.1.1
        with:
          role-to-assume: ${{ env.PROD_PIPELINE_EXECUTION_ROLE }}
          role-session-name: prod-packaging
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload artifacts to production artifact buckets
        run: |
          sam package \
            --s3-bucket ${PROD_ARTIFACTS_BUCKET} \
            --region ${AWS_REGION} \
            --output-template-file packaged-prod.yml

      - uses: actions/upload-artifact@v6
        with:
          name: packaged-prod.yml
          path: backend/packaged-prod.yml
          if-no-files-found: error

  deploy-testing-api:
    if: github.ref == 'refs/heads/main'
    needs: [build-and-package-prod-api]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v6
      - uses: aws-actions/setup-sam@v3
        with:
          use-installer: true
      - uses: actions/download-artifact@v8
        with:
          name: packaged-testing.yml
          path: backend

      - name: Assume the testing pipeline user role
        uses: aws-actions/configure-aws-credentials@v6.1.1
        with:
          role-to-assume: ${{ env.TESTING_PIPELINE_EXECUTION_ROLE }}
          role-session-name: deploy-testing-api
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to testing account
        run: |
          sam deploy \
            --stack-name ${TESTING_STACK_NAME} \
            --template packaged-testing.yml \
            --capabilities CAPABILITY_IAM \
            --region ${AWS_REGION} \
            --s3-bucket ${TESTING_ARTIFACTS_BUCKET} \
            --no-fail-on-empty-changeset \
            --role-arn ${TESTING_CLOUDFORMATION_EXECUTION_ROLE} \
            --parameter-overrides \
              ParameterKey=Env,ParameterValue=test \
              ParameterKey=PipelineRole,ParameterValue=${TESTING_PIPELINE_EXECUTION_ROLE} \
              ParameterKey=PushNotificationPublicKey,ParameterValue=${PUSH_NOTIFICATION_PUBLIC_KEY} \
              ParameterKey=PushNotificationPrivateKey,ParameterValue=${PUSH_NOTIFICATION_PRIVATE_KEY}

  integration-test:
    if: github.ref == 'refs/heads/main'
    needs: [deploy-testing-api]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v6
      - name: Run integration tests
        run: |
          # trigger the integration tests here

  deploy-prod-api:
    if: github.ref == 'refs/heads/main'
    needs: [integration-test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    outputs:
      web-endpoint: ${{ steps.set-env-vars.outputs.WebEndpoint }}
      api-endpoint: ${{ steps.set-env-vars.outputs.ApiEndpoint }}
    # Configure GitHub Action Environment to have a manual approval step before deployment to production
    # https://docs.github.com/en/actions/reference/environments
    # environment: <configured-environment>
    steps:
      - uses: actions/checkout@v6
      - uses: aws-actions/setup-sam@v3
        with:
          use-installer: true
      - uses: actions/download-artifact@v8
        with:
          name: packaged-prod.yml
          path: backend

      - name: Assume the prod pipeline user role
        uses: aws-actions/configure-aws-credentials@v6.1.1
        with:
          role-to-assume: ${{ env.PROD_PIPELINE_EXECUTION_ROLE }}
          role-session-name: deploy-prod-api
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to production account
        run: |
          sam deploy \
            --stack-name ${PROD_STACK_NAME} \
            --template packaged-prod.yml \
            --capabilities CAPABILITY_IAM \
            --region ${AWS_REGION} \
            --s3-bucket ${PROD_ARTIFACTS_BUCKET} \
            --no-fail-on-empty-changeset \
            --role-arn ${PROD_CLOUDFORMATION_EXECUTION_ROLE} \
            --parameter-overrides \
              ParameterKey=Env,ParameterValue=prod \
              ParameterKey=PipelineRole,ParameterValue=${PROD_PIPELINE_EXECUTION_ROLE} \
              ParameterKey=PushNotificationPublicKey,ParameterValue=${PUSH_NOTIFICATION_PUBLIC_KEY} \
              ParameterKey=PushNotificationPrivateKey,ParameterValue=${PUSH_NOTIFICATION_PRIVATE_KEY}

      - name: Get stack outputs
        id: set-env-vars
        shell: bash
        run: |
          aws cloudformation describe-stacks \
            --region us-east-1 \
            --stack-name ${PROD_STACK_NAME} \
            --output json \
            --query \
              'Stacks[0].Outputs' | \
              jq -cr '.[] | "\(.OutputKey)=\(.OutputValue)"' | \
              while read i; do
                echo $i
                echo $i >> "$GITHUB_OUTPUT"
              done

  deploy-prod-frontend:
    if: github.ref == 'refs/heads/main'
    needs: [deploy-prod-api]
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - name: Install dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile
      - name: Set environment variables
        working-directory: frontend
        run: |
          echo "VITE_BASE_URL=\"${{ needs.deploy-prod-api.outputs.web-endpoint }}\"" >> .env.production
          echo "VITE_API_URL=\"${{ needs.deploy-prod-api.outputs.api-endpoint }}\"" >> .env.production
          echo "VITE_CLERK_PUBLISHABLE_KEY=\"${{ vars.CLERK_PUBLIC_KEY }}\"" >> .env.production
          echo "VITE_STRIPE_PUBLIC_KEY=\"${{ vars.STRIPE_PUBLIC_KEY }}\"" >> .env.production
          echo "VITE_STRIPE_ALL_OWNED_LIGHT_PRICING_TABLE_ID=\"${{ vars.STRIPE_ALL_OWNED_LIGHT_PRICING_TABLE_ID }}\"" >> .env.production
          echo "VITE_STRIPE_25_OWNED_LIGHT_PRICING_TABLE_ID=\"${{ vars.STRIPE_25_OWNED_LIGHT_PRICING_TABLE_ID }}\"" >> .env.production
          echo "VITE_STRIPE_10_OWNED_LIGHT_PRICING_TABLE_ID=\"${{ vars.STRIPE_10_OWNED_LIGHT_PRICING_TABLE_ID }}\"" >> .env.production
          echo "VITE_STRIPE_BASE_LIGHT_PRICING_TABLE_ID=\"${{ vars.STRIPE_BASE_LIGHT_PRICING_TABLE_ID }}\"" >> .env.production
          echo "VITE_STRIPE_ALL_OWNED_DARK_PRICING_TABLE_ID=\"${{ vars.STRIPE_ALL_OWNED_DARK_PRICING_TABLE_ID }}\"" >> .env.production
          echo "VITE_STRIPE_25_OWNED_DARK_PRICING_TABLE_ID=\"${{ vars.STRIPE_25_OWNED_DARK_PRICING_TABLE_ID }}\"" >> .env.production
          echo "VITE_STRIPE_10_OWNED_DARK_PRICING_TABLE_ID=\"${{ vars.STRIPE_10_OWNED_DARK_PRICING_TABLE_ID }}\"" >> .env.production
          echo "VITE_STRIPE_BASE_DARK_PRICING_TABLE_ID=\"${{ vars.STRIPE_BASE_DARK_PRICING_TABLE_ID }}\"" >> .env.production
      - name: Build frontend
        run: CI=true yarn build
      - name: Assume the prod pipeline user role
        uses: aws-actions/configure-aws-credentials@v6.1.1
        with:
          role-to-assume: ${{ env.PROD_PIPELINE_EXECUTION_ROLE }}
          role-session-name: deploy-prod-frontend
          aws-region: ${{ env.AWS_REGION }}
      - name: Clear frontend bucket
        run: |
          aws s3 rm s3://itson.fyi --recursive
      - name: Deploy frontend
        run: |
          aws s3 cp dist \
            s3://itson.fyi \
            --recursive
