name: Push Dev

on:
  push:
    branches:
      - "dev"

env:
  AWS_SNS_COGNITO_IAM_ARN: ${{ secrets.AWS_SNS_COGNITO_IAM_ARN }}
  AWS_SNS_COGNITO_IAM_ROLE_EXTERNAL_ID: ${{ secrets.AWS_SNS_COGNITO_IAM_ROLE_EXTERNAL_ID }}
  AWS_SES_DOMAIN_IDENTITY_ARN: ${{ secrets.AWS_SES_DOMAIN_IDENTITY_ARN }}
  PIPELINE_USER_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  PIPELINE_USER_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SAM_TEMPLATE: template.yaml
  DEV_STACK_NAME: its-on-dev
  TESTING_PIPELINE_EXECUTION_ROLE: arn:aws:iam::303579314896:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1EXGMRU8M7PIU
  TESTING_CLOUDFORMATION_EXECUTION_ROLE: arn:aws:iam::303579314896:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-13FN6CKHSS9UA
  TESTING_ARTIFACTS_BUCKET: aws-sam-cli-managed-dev-pipeline-artifactsbucket-1awxr7qt59hmv
  # If there are functions with "Image" PackageType in your template,
  # uncomment the line below and add "--image-repository ${TESTING_IMAGE_REPOSITORY}" to
  # testing "sam package" and "sam deploy" commands.
  # TESTING_IMAGE_REPOSITORY = '0123456789.dkr.ecr.region.amazonaws.com/repository-name'
  TESTING_REGION: us-east-1

jobs:
  test-backend:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: npm install
      - run: npm test --silent

  test-frontend:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: npm install
      - run: CI=true npm test

  build-and-package-dev-api:
    if: github.ref == 'refs/heads/dev'
    needs: [test-backend, test-frontend]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Build resources
        run: |
          sam build \
            --template ${SAM_TEMPLATE} \
            --use-container \
            --parameter-overrides \
              ParameterKey=Env,ParameterValue=dev \
              ParameterKey=PipelineRole,ParameterValue=${TESTING_PIPELINE_EXECUTION_ROLE} \
              ParameterKey=SnsCognitoIamArn,ParameterValue=${AWS_SNS_COGNITO_IAM_ARN} \
              ParameterKey=SnsCognitoIamExternalId,ParameterValue=${AWS_SNS_COGNITO_IAM_ROLE_EXTERNAL_ID} \
              ParameterKey=SESDomainIdentityArn,ParameterValue=${AWS_SES_DOMAIN_IDENTITY_ARN}

      - name: Assume the testing pipeline user role
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ env.PIPELINE_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.PIPELINE_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.TESTING_REGION }}
          role-to-assume: ${{ env.TESTING_PIPELINE_EXECUTION_ROLE }}
          role-session-name: dev-packaging
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Upload artifacts to testing artifact buckets
        run: |
          sam package \
            --s3-bucket ${TESTING_ARTIFACTS_BUCKET} \
            --region ${TESTING_REGION} \
            --output-template-file packaged-dev.yaml

      - uses: actions/upload-artifact@v3
        with:
          name: packaged-dev.yaml
          path: backend/packaged-dev.yaml
          if-no-files-found: error

  deploy-dev-api:
    if: github.ref == 'refs/heads/dev'
    needs: [build-and-package-dev-api]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    outputs:
      cognito-client-id: ${{ steps.set-env-vars.outputs.CognitoClientID }}
      web-endpoint: ${{ steps.set-env-vars.outputs.WebEndpoint }}
      auth-endpoint: ${{ steps.set-env-vars.outputs.AuthEndpoint }}
      api-endpoint: ${{ steps.set-env-vars.outputs.ApiEndpoint }}
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: actions/download-artifact@v3
        with:
          name: packaged-dev.yaml
          path: backend

      - name: Assume the testing pipeline user role
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ env.PIPELINE_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.PIPELINE_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.TESTING_REGION }}
          role-to-assume: ${{ env.TESTING_PIPELINE_EXECUTION_ROLE }}
          role-session-name: deploy-dev-api
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Deploy to testing account
        run: |
          sam deploy \
            --stack-name ${DEV_STACK_NAME} \
            --template packaged-dev.yaml \
            --capabilities CAPABILITY_IAM \
            --region ${TESTING_REGION} \
            --s3-bucket ${TESTING_ARTIFACTS_BUCKET} \
            --no-fail-on-empty-changeset \
            --role-arn ${TESTING_CLOUDFORMATION_EXECUTION_ROLE} \
            --parameter-overrides \
              ParameterKey=Env,ParameterValue=dev \
              ParameterKey=PipelineRole,ParameterValue=${TESTING_PIPELINE_EXECUTION_ROLE} \
              ParameterKey=SnsCognitoIamArn,ParameterValue=${AWS_SNS_COGNITO_IAM_ARN} \
              ParameterKey=SnsCognitoIamExternalId,ParameterValue=${AWS_SNS_COGNITO_IAM_ROLE_EXTERNAL_ID} \
              ParameterKey=SESDomainIdentityArn,ParameterValue=${AWS_SES_DOMAIN_IDENTITY_ARN}

      - name: Get stack outputs
        id: set-env-vars
        shell: bash
        run: |
          aws cloudformation describe-stacks \
            --region us-east-1 \
            --stack-name ${DEV_STACK_NAME} \
            --output json \
            --query \
              'Stacks[0].Outputs' | \
              jq -cr '.[] | "\(.OutputKey)=\(.OutputValue)"' | \
              while read i; do
                echo $i
                echo $i >> "$GITHUB_OUTPUT"
              done

  deploy-dev-frontend:
    if: github.ref == 'refs/heads/dev'
    needs: [deploy-dev-api]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: npm install
      - name: Set environment variables
        working-directory: frontend
        run: |
          echo "REACT_APP_COGNITO_CLIENT_ID=\"${{needs.deploy-dev-api.outputs.cognito-client-id}}\"" >> .env.production
          echo "REACT_APP_BASE_URL=\"${{needs.deploy-dev-api.outputs.web-endpoint}}\"" >> .env.production
          echo "REACT_APP_AUTH_URL=\"${{needs.deploy-dev-api.outputs.auth-endpoint}}\"" >> .env.production
          echo "REACT_APP_API_URL=\"${{needs.deploy-dev-api.outputs.api-endpoint}}\"" >> .env.production
      - name: Build frontend
        run: CI=true npm run build

      - name: Assume the testing pipeline user role
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ env.PIPELINE_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.PIPELINE_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.TESTING_REGION }}
          role-to-assume: ${{ env.TESTING_PIPELINE_EXECUTION_ROLE }}
          role-session-name: deploy-dev-frontend
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Clear frontend bucket
        run: |
          aws s3 rm s3://dev.itson.fyi --recursive
      - name: Deploy frontend
        run: |
          aws s3 cp build \
            s3://dev.itson.fyi \
            --recursive
